**Regression Metrics**

Metrics for regression involve calculating an error score to summarize the predictive skill of a model. How to calculate and report mean squared error, root mean squared error, and mean absolute error.

In [1]:
#load dataset
import pandas as pd
import numpy as np
df=pd.read_csv('weight.csv')
df

,age,height,weight
0,45,5.00,77
1,26,5.11,47
2,30,5.60,55
3,34,5.90,59
4,40,4.80,72
5,36,5.80,60
6,19,5.30,40
7,28,5.80,60
8,23,5.50,45
9,32,5.60,58


In [2]:
#separate input and output
X=df.drop('weight',axis=True)
Y=df['weight']

**Mean Absolute Error**

The absolute error is the absolute value of the difference between the forecasted value and the actual value. MAE tells us how big of an error we can expect from the forecast on average. 

The closer MAE is to 0, the more accurate the model is. But MAE is returned on the same scale as the target you are predicting for and therefore there isn't a general rule for what a good score is. How good your score is can only be evaluated within your dataset.

In [3]:
# Cross Validation Regression MAE
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
kfold = KFold(n_splits=10, shuffle=True)
model = LinearRegression()
scoring = 'neg_mean_absolute_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([-0.54427421, -4.33037491, -2.64121544, -9.48797309, -0.20701934,
       -0.84970593, -4.10218835, -0.33891559, -0.43713631, -5.13852771])

In [4]:
results.mean()

-2.8077330876006052

In [5]:
results.std()

2.855093835180994

**Mean Squared Error**

The Mean Squared Error measures how close a regression line is to a set of data points. It is a risk function corresponding to the expected value of the squared error loss. Mean square error is calculated by taking the average, specifically the mean, of errors squared from data as it relates to a function.

There is no correct value for MSE. Simply put, the lower the value the better and 0 means the model is perfect.

In [6]:
kfold = KFold(n_splits=10, shuffle=True)
model = LinearRegression()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([-1.91088150e-01, -2.96234416e-01, -1.14863777e-01, -1.87521469e+01,
       -2.64044671e+01, -6.97601898e+00, -9.00216333e+01, -7.22000171e-01,
       -1.68279493e+01, -4.28570070e-02])

In [7]:
results.mean()

-16.034925898895743

In [8]:
results.std()

26.294581510018645

**R2 Metric**

R2 tells us how well the predictor variables can explain the variation in the response variable.

If the value of the r squared score is 1, it means that the model is perfect and if its value is 0, it means that the model will perform badly on an unseen dataset. This also implies that the closer the value of the r squared score is to 1, the more perfectly the model is trained.

In [9]:
kfold = KFold(n_splits=10, shuffle=True)
model = LinearRegression()
scoring = 'r2'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetri

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [10]:
results.mean()

nan

In [11]:
results.std()

nan