**Spot-Check Classification Algorithms**

**Spot-checking** is a way of discovering which algorithms perform well on your machine learning problem.

You cannot know which algorithms are best suited to your problem before hand. You must trial a number of methods and focus attention on those that prove themselves the most promising.

You must use trial and error to discover a short list of algorithms that do well on your problem that you can then double down on and tune further. I call this process spot checking.

In [2]:
import pandas as pd
import numpy as np
#Add labels
filename='diabetes.csv'
names=['preg','glu','bp','skin','insulin','bmi','pedi','age','class']
df=pd.read_csv(filename,names=names)
df

,preg,glu,bp,skin,insulin,bmi,pedi,age,class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


In [3]:
#separate input and output
X=df.drop('class',axis=True)
Y=df['class']

# **Algorithms Overview**
We are going to take a look at 6 classification algorithms that you can spot check on your dataset.

2 Linear Machine Learning Algorithms: Logistic Regression
and Linear Discriminant Analysis

4 Nonlinear Machine Learning Algorithms: K-Nearest Neighbors, Naive Bayes, Classification and Regression Trees, Support Vector Machines

**Logistic Regression**

Logistic regression is an example of supervised learning. It is used to calculate or predict the probability of a binary (yes/no) event occurring. An example of logistic regression could be applying machine learning to determine if a person is likely to be infected with COVID-19 or not.

Linear regression is utilized for regression tasks, while logistic regression helps accomplish classification tasks.

**How do you interpret logistic regression?**

If the intercept has a negative sign: then the probability of having the outcome will be < 0.5. If the intercept has a positive sign: then the probability of having the outcome will be > 0.5. If the intercept is equal to zero: then the probability of having the outcome will be exactly 0.5.

In [4]:
# Logistic Regression Classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
kfold = KFold(n_splits=10, shuffle=True)
model = LogisticRegression()
results = cross_val_score(model, X, Y, cv=kfold)
results

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

array([0.71428571, 0.79220779, 0.77922078, 0.7012987 , 0.75324675,
       0.83116883, 0.71428571, 0.83116883, 0.80263158, 0.80263158])

In [5]:
results.mean()

0.7722146274777854

**Linear Discriminant Analysis**

PCA is an unsupervised learning algorithm while LDA is a supervised learning algorithm. This means that PCA finds directions of maximum variance regardless of class labels while LDA finds directions of maximum class separability.

The results of an LDA give probability distributions for the topics over the vocabulary. In practice this means a list of words from the vocabulary, each with a probability associated with it. We can of course list the words in order of decreasing probability, and look at the top j words per topic for some j.

In [6]:
# LDA Classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
kfold = KFold(n_splits=10, shuffle=True)
model = LinearDiscriminantAnalysis()
results = cross_val_score(model, X, Y, cv=kfold)
results

array([0.75324675, 0.80519481, 0.79220779, 0.7012987 , 0.75324675,
       0.72727273, 0.75324675, 0.85714286, 0.78947368, 0.84210526])

In [7]:
results.mean()

0.7774436090225564

**k-Nearest Neighbors**

The k-nearest neighbors algorithm, also known as KNN or k-NN, is a non-parametric, supervised learning classifier, which uses proximity to make classifications or predictions about the grouping of an individual data point.

In [8]:
# KNN Classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
kfold = KFold(n_splits=10, shuffle=True)
model = KNeighborsClassifier()
results = cross_val_score(model, X, Y, cv=kfold)
results

array([0.71428571, 0.67532468, 0.79220779, 0.72727273, 0.71428571,
       0.67532468, 0.7012987 , 0.7012987 , 0.77631579, 0.65789474])

In [9]:
results.mean()

0.713550922761449

**Naive Bayes**

It is a probabilistic classifier, which means it predicts on the basis of the probability of an object.

In [10]:
# Gaussian Naive Bayes Classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
kfold = KFold(n_splits=10, shuffle=True)
model = GaussianNB()
results = cross_val_score(model, X, Y, cv=kfold)
results

array([0.68831169, 0.75324675, 0.76623377, 0.77922078, 0.81818182,
       0.79220779, 0.74025974, 0.75324675, 0.65789474, 0.78947368])

In [11]:
results.mean()

0.7538277511961723

**Classification and Regression Trees**

CART is a predictive algorithm used in Machine learning and it explains how the target variable's values can be predicted based on other matters. It is a decision tree where each fork is split into a predictor variable and each node has a prediction for the target variable at the end.

In [12]:
# CART Classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
kfold = KFold(n_splits=10, shuffle=True)
model = DecisionTreeClassifier()
results = cross_val_score(model, X, Y, cv=kfold)
results

array([0.67532468, 0.75324675, 0.7012987 , 0.76623377, 0.71428571,
       0.7012987 , 0.74025974, 0.75324675, 0.73684211, 0.76315789])

In [13]:
results.mean()

0.7305194805194806

**Support Vector Machines**

Support Vector Machine(SVM) is a supervised machine learning algorithm used for both classification and regression. Though we say regression problems as well its best suited for classification. The objective of SVM algorithm is to find a hyperplane in an N-dimensional space that distinctly classifies the data points.

In [14]:
# SVM Classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
kfold = KFold(n_splits=10, shuffle=True)
model = SVC()
results = cross_val_score(model, X, Y, cv=kfold)
results

array([0.77922078, 0.77922078, 0.67532468, 0.75324675, 0.81818182,
       0.76623377, 0.75324675, 0.75324675, 0.78947368, 0.73684211])

In [15]:
results.mean()

0.7604237867395762