**Spot Check Machine Learning Based Classification**

Spot-checking is a way of discovering which algorithms perform well on your machine learning problem.

You cannot know which algorithms are best suited to your problem before hand. You must trial a number of methods and focus attention on those that prove themselves the most promising.

In [1]:
#load dataset
import pandas as pd
import numpy as np
df=pd.read_csv('weight.csv')
df

,age,height,weight
0,45,5.00,77
1,26,5.11,47
2,30,5.60,55
3,34,5.90,59
4,40,4.80,72
5,36,5.80,60
6,19,5.30,40
7,28,5.80,60
8,23,5.50,45
9,32,5.60,58


In [2]:
#separate input and output
X=df.drop('weight',axis=True)
Y=df['weight']     

# **Algorithms Overview**
We are going to take a look at 7 classification algorithms that you can spot check on your dataset.

4 Linear Machine Learning Algorithms: Linear Regression, Ridge Regression, LASSO Linear Regression, Elastic Net Regression

3 Nonlinear Machine Learning Algorithms: K-Nearest Neighbors, Classification and Regression Trees, Support Vector Machines

**Linear Regression**

Linear Regression is a machine learning algorithm based on supervised learning. It performs a regression task. Regression models a target prediction value based on independent variables. It is mostly used for finding out the relationship between variables and forecasting.

**Why is scoring set to “neg_mean_squared_error”?**

This means that a negative value is a prefix to all mse calculations. The mse cannot return negative values. Although the difference between one value and the mean can be negative, this negative value is squared. Therefore all results are either positive or zero.

In [3]:
# Linear Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
kfold = KFold(n_splits=10, shuffle=True)
model = LinearRegression()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([-2.96234416e-01, -1.68279493e+01, -7.22000171e-01, -1.91088150e-01,
       -2.64044671e+01, -1.87521469e+01, -4.28570070e-02, -6.97601898e+00,
       -9.00216333e+01, -1.14863777e-01])

In [4]:
results.mean()

-16.034925898895743

**Ridge Regression**

Ridge regression is a method of estimating the coefficients of multiple-regression models in scenarios where the independent variables are highly correlated. It has been used in many fields including econometrics, chemistry, and engineering.

Lasso tends to do well if there are a small number of significant parameters and the others are close to zero (ergo: when only a few predictors actually influence the response). Ridge works well if there are many large parameters of about the same value (ergo: when most predictors impact the response).

Ridge regression is a method to perform linear regression with fewer chances of a model getting into problems such as underfitting or overfitting.

In [5]:
# Ridge Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Ridge
kfold = KFold(n_splits=10, shuffle=True)
model = Ridge()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([-1.48869147e+01, -2.31927183e+01, -5.43025742e-02, -6.47796979e-02,
       -1.32898958e+01, -7.38695352e-01, -5.17933292e-01, -2.31446364e-01,
       -6.15405519e+00, -7.95865516e+01])

In [6]:
results.mean()

-13.871729280898094

**LASSO Regression**

The lasso regression allows you to shrink or regularize these coefficients to avoid overfitting and make them work better on different datasets. This type of regression is used when the dataset shows high multicollinearity or when you want to automate variable elimination and feature selection.

Ridge and lasso regression are two common machine learning approaches for constraining model parameters. Both methods try to get the coefficient estimates as close to zero as possible because minimizing (or shrinking) coefficients can reduce variance dramatically (i.e., overfitting)

In [7]:
# Lasso Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Lasso
kfold = KFold(n_splits=10, shuffle=True)
model = Lasso()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([ -0.97135746, -11.6760344 ,  -0.30238935, -68.50463637,
        -5.35648353, -19.84977325,  -0.10711772,  -1.3804361 ,
       -11.93375083,  -0.09210774])

In [8]:
results.mean()

-12.01740867544289

**ElasticNet Regression**

Elastic net linear regression uses the penalties from both the lasso and ridge techniques to regularize regression models. The technique combines both the lasso and ridge regression methods by learning from their shortcomings to improve the regularization of statistical models.

Elastic net is always preferred over lasso & ridge regression because it solves the limitations of both methods, while also including each as special cases. So if the ridge or lasso solution is, indeed, the best, then any good model selection routine will identify that as part of the modeling process.

In [9]:
# ElasticNet Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import ElasticNet
kfold = KFold(n_splits=10, shuffle=True)
model = ElasticNet()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([-12.05793252,  -0.30739893,  -1.03604573,  -0.15018519,
        -0.09062827,  -1.55131156, -68.28534909, -11.8875995 ,
       -19.68246349,  -5.31105027])

In [10]:
results.mean()

-12.035996455103405

**K-Nearest Neighbors**

In k-NN regression, the k-NN algorithm is used for estimating continuous variables. One such algorithm uses a weighted average of the k nearest neighbors, weighted by the inverse of their distance.

In [11]:
# KNN Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor
kfold = KFold(n_splits=10, shuffle=True)
model = KNeighborsRegressor()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([ -51.84, -262.44,   -4.  ,   -3.24,   -3.24, -169.  , -104.04,
         -0.64,  -49.  ,  -21.16])

In [12]:
results.mean()

-66.86000000000003

**Classification and Regression Trees (CART)**

CART is a predictive algorithm used in Machine learning and it explains how the target variable's values can be predicted based on other matters. It is a decision tree where each fork is split into a predictor variable and each node has a prediction for the target variable at the end.

In [13]:
# Decision Tree Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
kfold = KFold(n_splits=10, shuffle=True)
model = DecisionTreeRegressor()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([  -9.,  -49.,   -1.,   -9.,  -25.,  -25.,   -1.,  -49., -100.,
       -196.])

In [14]:
results.mean()

-46.4

**Support Vector Machines**

In general, you can use SVR to solve the same problems you would use linear regression for. Unlike linear regression, though, SVR also allows you to model non-linear relationships between variables and provides the flexibility to adjust the model's robustness by tuning hyperparameters.

In [15]:
# SVM Regression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
kfold = KFold(n_splits=10, shuffle=True)
model = SVR()
scoring = 'neg_mean_squared_error'
results = cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
results

array([  -0.37264789, -115.97119598,   -8.17808996, -158.25893983,
       -309.1952338 , -318.09171129,   -1.62163753,   -0.37761896,
       -164.61382942,  -10.71208664])

In [16]:
results.mean()

-108.7392991288159